//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voter.Database.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoterConnection : DbContext
    {
        public VoterConnection()
            : base("name=VoterConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Ballet> Ballets { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Constituency> Constituencies { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserInConstituencyMapping> UserInConstituencyMappings { get; set; }
        public virtual DbSet<VoterProfile> VoterProfiles { get; set; }
    }
}
